name: sportsfilter
description: Filter Sports bet.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.0.0+1
  cloud_firestore: ^0.12.7
  firebase_auth: ^0.11.1+8
  # Mostrar Toast Msg
  overlay_support: ^1.0.0
  # Para mostrar HUD (ventanas en espera)
  modal_progress_hud: ^0.1.3
  # Consultas Linq
  queries: ^0.1.12
  # Seleccion de texto (copy/paste)
  flutter_selectable_text: ^0.3.1
  # Localizacion para idioma y fechas
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # Fonts
  fonts:
    - family: ShareTech
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf
  